### ISSUE TITLE
Missing Centaur.sql file?

### ISSUE THREAD

**Issue by pwlkram** [howardpchen/Centaur#1]
In readme for Centaur repository you mention creating new table in MySQL database using Centaur.sql. As I understand it there should be a "Centaur.sql" file in repository that creates correctly organized table. Am I right? If yes, could I ask you to add the missing file, please?
Or did I miss something?

**Comment by howardpchen** [comment]
Yes you are correct.  I uploaded the file now.

**Comment by pwlkram** [comment]
Thank you for such a prompt response.
